# Generated by Django 2.1.3 on 2018-12-03 06:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_auto_20181203_0606'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostScience',
            new_name='Post',
        ),
        migrations.RemoveField(
            model_name='posttechnologies',
            name='author',
        ),
        migrations.RemoveField(
            model_name='posttechnologies',
            name='category',
        ),
        migrations.DeleteModel(
            name='PostTechnologies',
        ),
    ]
