# Generated by Django 2.1.3 on 2018-12-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20181206_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='detail/', width_field=100),
        ),
    ]
